{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "test-app.fullname" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    release: monitoring
    {{- include "test-app.labels" . | nindent 4 }}
spec:
  endpoints:
  - path: /metrics
    port: web
  selector:
    matchLabels:
      {{- include "test-app.selectorLabels" . | nindent 6 }}
{{- end }}